// src/services/api.ts
import { Customer, Order, Product as ProductType, Expense } from '../types';

// IMPORTANT: Replace this with your actual Cloud Functions base URL after deployment
// For local development with Firebase Emulator, it's typically:
// const API_BASE_URL = 'http://127.0.0.1:5001/{your-firebase-project-id}/{your-region}/api';
// For deployed functions, it will look like:
// const API_BASE_URL = 'https://{your-region}-{your-firebase-project-id}.cloudfunctions.net/api';
// Using a placeholder that will likely fail, to remind user to configure it.
const API_BASE_URL = 'YOUR_CLOUD_FUNCTIONS_API_BASE_URL_HERE/api';

interface ApiErrorData {
  error: string;
  details?: any;
}

class ApiError extends Error {
  status: number;
  data: ApiErrorData;

  constructor(message: string, status: number, data: ApiErrorData) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.data = data;
  }
}

const handleResponse = async <T>(response: Response): Promise<T> => {
  const contentType = response.headers.get('content-type');
  let responseData;

  if (contentType && contentType.includes('application/json')) {
    responseData = await response.json();
  } else {
    // Handle non-JSON responses, e.g. plain text for simple messages
    responseData = await response.text();
  }

  if (!response.ok) {
    const errorMessage = responseData?.error || responseData || `HTTP error! status: ${response.status}`;
    console.error('API Error:', response.status, responseData);
    throw new ApiError(errorMessage, response.status, responseData);
  }
  return responseData as T;
};

const getHeaders = () => {
  return {
    'Content-Type': 'application/json',
    // Add any other headers like Authorization if needed in the future
  };
};

// --- Customer API ---
export const createCustomer = async (customerData: Omit<Customer, 'id' | 'createdAt'> & { createdAt: string }): Promise<Customer> => {
  const response = await fetch(`${API_BASE_URL}/customers`, {
    method: 'POST',
    headers: getHeaders(),
    body: JSON.stringify(customerData),
  });
  return handleResponse<Customer>(response);
};

export const getCustomers = async (): Promise<Customer[]> => {
  const response = await fetch(`${API_BASE_URL}/customers`, {
    method: 'GET',
    headers: getHeaders(),
  });
  return handleResponse<Customer[]>(response);
};

export const getCustomerById = async (id: string): Promise<Customer> => {
  const response = await fetch(`${API_BASE_URL}/customers/${id}`, {
    method: 'GET',
    headers: getHeaders(),
  });
  return handleResponse<Customer>(response);
};

export const updateCustomer = async (id: string, customerData: Partial<Omit<Customer, 'id'>>): Promise<Customer> => {
  const response = await fetch(`${API_BASE_URL}/customers/${id}`, {
    method: 'PUT',
    headers: getHeaders(),
    body: JSON.stringify(customerData),
  });
  return handleResponse<Customer>(response);
};

export const deleteCustomer = async (id: string): Promise<{ message: string }> => {
  const response = await fetch(`${API_BASE_URL}/customers/${id}`, {
    method: 'DELETE',
    headers: getHeaders(),
  });
  return handleResponse<{ message: string }>(response);
};

// --- Order API ---
export const createOrder = async (orderData: Omit<Order, 'id' | 'orderNumber'> & { orderNumber?: string }): Promise<Order> => {
  // orderNumber can be generated by backend, but allow frontend to suggest one if needed
  const payload = { ...orderData, orderNumber: orderData.orderNumber || `ORD-${Date.now()}` };
  const response = await fetch(`${API_BASE_URL}/orders`, {
    method: 'POST',
    headers: getHeaders(),
    body: JSON.stringify(payload),
  });
  return handleResponse<Order>(response);
};

export const getOrders = async (): Promise<Order[]> => {
  const response = await fetch(`${API_BASE_URL}/orders`, {
    method: 'GET',
    headers: getHeaders(),
  });
  return handleResponse<Order[]>(response);
};

export const getOrderById = async (id: string): Promise<Order> => {
  const response = await fetch(`${API_BASE_URL}/orders/${id}`, {
    method: 'GET',
    headers: getHeaders(),
  });
  return handleResponse<Order>(response);
};

export const updateOrder = async (id: string, orderData: Partial<Omit<Order, 'id'>>): Promise<Order> => {
  const response = await fetch(`${API_BASE_URL}/orders/${id}`, {
    method: 'PUT',
    headers: getHeaders(),
    body: JSON.stringify(orderData),
  });
  return handleResponse<Order>(response);
};

export const deleteOrder = async (id: string): Promise<{ message: string }> => {
  const response = await fetch(`${API_BASE_URL}/orders/${id}`, {
    method: 'DELETE',
    headers: getHeaders(),
  });
  return handleResponse<{ message: string }>(response);
};

// --- Product API ---
export const createProduct = async (productData: Omit<ProductType, 'id'>): Promise<ProductType> => {
  const response = await fetch(`${API_BASE_URL}/products`, {
    method: 'POST',
    headers: getHeaders(),
    body: JSON.stringify(productData),
  });
  return handleResponse<ProductType>(response);
};

export const getProducts = async (): Promise<ProductType[]> => {
  const response = await fetch(`${API_BASE_URL}/products`, {
    method: 'GET',
    headers: getHeaders(),
  });
  return handleResponse<ProductType[]>(response);
};

export const getProductById = async (id: string): Promise<ProductType> => {
  const response = await fetch(`${API_BASE_URL}/products/${id}`, {
    method: 'GET',
    headers: getHeaders(),
  });
  return handleResponse<ProductType>(response);
};

export const updateProduct = async (id: string, productData: Partial<Omit<ProductType, 'id'>>): Promise<ProductType> => {
  const response = await fetch(`${API_BASE_URL}/products/${id}`, {
    method: 'PUT',
    headers: getHeaders(),
    body: JSON.stringify(productData),
  });
  return handleResponse<ProductType>(response);
};

export const deleteProduct = async (id: string): Promise<{ message: string }> => {
  const response = await fetch(`${API_BASE_URL}/products/${id}`, {
    method: 'DELETE',
    headers: getHeaders(),
  });
  return handleResponse<{ message: string }>(response);
};

// --- Expense API ---
export const createExpense = async (expenseData: Omit<Expense, 'id'>): Promise<Expense> => {
  const response = await fetch(`${API_BASE_URL}/expenses`, {
    method: 'POST',
    headers: getHeaders(),
    body: JSON.stringify(expenseData),
  });
  return handleResponse<Expense>(response);
};

export const getExpenses = async (): Promise<Expense[]> => {
  const response = await fetch(`${API_BASE_URL}/expenses`, {
    method: 'GET',
    headers: getHeaders(),
  });
  return handleResponse<Expense[]>(response);
};

export const getExpenseById = async (id: string): Promise<Expense> => {
  const response = await fetch(`${API_BASE_URL}/expenses/${id}`, {
    method: 'GET',
    headers: getHeaders(),
  });
  return handleResponse<Expense>(response);
};

export const updateExpense = async (id: string, expenseData: Partial<Omit<Expense, 'id'>>): Promise<Expense> => {
  const response = await fetch(`${API_BASE_URL}/expenses/${id}`, {
    method: 'PUT',
    headers: getHeaders(),
    body: JSON.stringify(expenseData),
  });
  return handleResponse<Expense>(response);
};

export const deleteExpense = async (id: string): Promise<{ message: string }> => {
  const response = await fetch(`${API_BASE_URL}/expenses/${id}`, {
    method: 'DELETE',
    headers: getHeaders(),
  });
  return handleResponse<{ message: string }>(response);
};

// It's good practice to also export the ApiError class if other parts of the app might want to catch it specifically
export { ApiError };
